#ifndef EXECUTOR_OPTIONS_H_Mfoim349fjrmntjvnmdsfm39ruinjnkdf3uhburehfvndskdcisnxciwunwecrevbuf43f4rfr54
#define EXECUTOR_OPTIONS_H_Mfoim349fjrmntjvnmdsfm39ruinjnkdf3uhburehfvndskdcisnxciwunwecrevbuf43f4rfr54

namespace executor
{
	void setup_options();
}

#endif