#ifndef EXECUTOR_OPTIONS_H_Mfoim349fjrmntjvnmdsfm39ruinjnkdf3uhburehfvndskdcisnxciwunwecrevbuf43f4rfr54
#define EXECUTOR_OPTIONS_H_Mfoim349fjrmntjvnmdsfm39ruinjnkdf3uhburehfvndskdcisnxciwunwecrevbuf43f4rfr54

#include <boost/program_options/options_description.hpp>

namespace executor
{
	boost::program_options::options_description setup_options();
}

#endif