set(CPACK_PACKAGE_NAME ${PROJECT_NAME} CACHE STRING "Package name")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A UI-based tool for log analysis")
set(CPACK_PACKAGE_VENDOR "Ratelware")

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/_packages")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_PACKAGE_CONTACT "tomasz.lewowski@ratelware.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Tomasz Lewowski")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

include(CPack)
