FUNCTION(SET_OUTPUT_DIRECTORIES TARGETS...)
    FOREACH(TARG ${TARGETS})
        SET_TARGET_PROPERTIES(${TARG} PROPERTIES 
            RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
            LIBRARY_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
            ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
	ENDFOREACH(TARG)
ENDFUNCTION(SET_OUTPUT_DIRECTORIES TARGETS...)